### PR TITLE
Task 2

### PR DESCRIPTION
**Pull request by MeroshiniRaja**
Automated deployment is done. Given the cloudfront url ans s3 url in readme file

### CODE REVIEW

**Comment by WizzyWu** [comment]
I checked your PR. Well done!

**Review by anyudenko — APPROVED** [review]
Reviewed. Your score is 5 (max).

**Review by Tasleem-web — COMMENTED** [review]
changes looks good.(Your score is 5)

**Comment by WizzyWu** [comment]
Your score is 5

**Pull request merged**
